### ISSUE TITLE
move to official project url?

### ISSUE THREAD

**Issue by r-lindner** [russellvt/pnp4nagios#5]
Hello,
I looked at all 110 pnp4nagios forks for changes after @lingej abandoned the project. There are 6 people who seem to add small things to their own current fork. Wouldn't it make sense to use the organization https://github.com/pnp4nagios and add the people that want to maintain it there? Than maybe lingej can add another comment to the readme pointing to the new official repo.

What are your thoughts @jimorie @pnp4nagios2  @tjyang @mtnielsen @learnmonitoring @Tontonitch

**Comment by jimorie** [comment]
Sounds like a good idea. I don't expect to come in touch with pnp4nagios for the foreseeable future, but I'll ping some colleagues that might.

**Comment by tjyang** [comment]
Hi All

I created pnp4ngios2 GitHub organization for testing/learning purpose. Definitely I will contribute to official pnp4nagios org and delete pnp4nagios2 later.  

Goals feasible for my skillset are:

- For local rpm testing: "./bootstrap.bash && make rpm" to get set of RPMs like the ones in EPEL.
- Be able run "sudo dnf install -y pnp4nagios" on RL8, this will need to work with existing RPM keeper on EPEL7 repo.

**Comment by mtnielsen** [comment]
Hi,
I have no real desire to maintain the project.
My one fix was just to get 0.6.26 to run on whichever PHP version is current on EPEL (can't remember).
You can have it if you want. :-)

**Comment by tjyang** [comment]
@mtnielsen , Thanks for the response.
Please post your patch somewhere.
On CentOS 7.9, it is php-5.4.16-48.el7.x86_64.
To re-activate this project we need  php/C dev and  ops ppl involved. 
Especially we need dev resources since kohana HMVC php framework is also defunct and koseven(work with php7+) is poised to succeed it.

**Comment by tjyang** [comment]
@r-lindner 

Would you mind take over and lead this project with my endorsement  ? 
If you agree, then we have at least two people to activate this project.

**Comment by r-lindner** [comment]
> Shouldn't we all get together and maintain pnp4nagios instead of creating a bunch of new forks?

That's why I opened this issue.

> I'll be willing to help! I'm not a "leader", but I got some experience in Perl/PHP. It will certainly take some time to get "in there", but I thing it is worth it!

And that's why I chose THIS fork for getting together.
From the readme:
> As a long-time user of pnpnagios, I am trying to give the project a good home as we try to further develop this project..

**Comment by russellvt** [comment]
> Would you mind take over and lead this project with my endorsement ? If you guys all agree then we can activate this project with 3 committed resources.

I am happy to try to take over pieces of this, along with @r-lindner (or whomever else would like to contribute). However, I *am not* currently a member of that project/organization ... so, if someone can convince @lingej to give us "deeper access" to that org, I am happy to work within it.

Otherwise, I think this is "just as good location as any other," until we establish a "new" master site or domain (if-appropriate). But, I am happy to help coordinate further development / improvement efforts as people would like for this code.

**Comment by russellvt** [comment]
Note: I have opened up the `Discussions` feature on this repo, and created #9 for continuing this set of questions, there.

I will be closing this out of the `Issues` category with this response (that's ***not*** a dismissal ... just a re-focus). Thank you all!!!
